name: daydreams

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/daydreams
      - CHROMA_ENDPOINT=http://chroma:8000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STARKNET_RPC_URL=${STARKNET_RPC_URL}
      - STARKNET_ADDRESS=${STARKNET_ADDRESS}
      - STARKNET_PRIVATE_KEY=${STARKNET_PRIVATE_KEY}
      - GRAPHQL_URL=${GRAPHQL_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CHROMA_URL=${CHROMA_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - HYPERLIQUID_MAIN_ADDRESS=${HYPERLIQUID_MAIN_ADDRESS}
      - HYPERLIQUID_WALLET_ADDRESS=${HYPERLIQUID_WALLET_ADDRESS}
      - HYPERLIQUID_PRIVATE_KEY=${HYPERLIQUID_PRIVATE_KEY}
    depends_on:
      mongo:
        condition: service_healthy
      chroma:
        condition: service_started
    command: pnpm start

  chroma:
    image: chromadb/chroma:0.6.3
    container_name: ${COMPOSE_PROJECT_NAME}_chroma
    restart: always
    ports:
      - "8000:8000"

  mongo:
    image: mongo:8.0.4
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["mongod", "--bind_ip_all", "--maxConns", "100"]
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=example